version: '3.3'
services:
  nct:
    image: nct
    container_name: nct
    privileged: true
    restart: always
    user: root
    environment:
      - ENV=prod
    ports:
      - '10010:10010' # http
      - '10011:10011' # ws
    volumes:
      - /root/ssh:/var/ssh
      - /root/logs/nct:/app/log
      - /root/static/nct:/app/www
